name: DevOps CI CD Aliyun ACR
on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unit Test
        run: |
          pip install -r requirements.txt
          pytest test_app.py

      - name: Get SHA
        id: getsha
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login Aliyun ACR
        run: |
          docker login crpi-ixkjro3paqt3g7zx.cn-hangzhou.personal.cr.aliyuncs.com \
            -u nick7719246840 \
            -p ${{ secrets.ALI_ACR_PWD }}

      - name: Build Push Image
        env:
          REG: crpi-ixkjro3paqt3g7zx.cn-hangzhou.personal.cr.aliyuncs.com
          NS: chenxiaoyu-demo
          SHA: ${{ env.SHA }}
        run: |
          docker build -t ${REG}/${NS}/se-web-app:latest .
          docker tag ${REG}/${NS}/se-web-app:latest ${REG}/${NS}/se-web-app:${SHA}
          docker push ${REG}/${NS}/se-web-app:latest
          docker push ${REG}/${NS}/se-web-app:${SHA}
